name: Project Init
on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install Vue CLI
        run: npm install -g @vue/cli
      - name: Create default Vue Project
        run: vue create -d --merge .
      - name: Set Git Author
        run: |
          git config --global user.name "Akuda"
          git config --global email "solutions@akuda.io"
      - name: Push Initial Commit
        run: |
          git commit -am "init: add default vue scafolding"
          git push
