name: Project Init
on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install Vue CLI
        run: npm install -g @vue/cli
      - name: Create default Vue Project
        run: vue create -d --merge .
